### ISSUE TITLE
Support WebGL2 context

### ISSUE THREAD

**Issue by skybluecat** [RonenNess/partykals#6]
Hi, I found that when using a WebGL2 context and partykals with texture, the shader doesn't compile because "texture" is a reserved word in WebGL2. Can you please fix that by renaming the variables texture?

**Comment by RonenNess** [comment]
Hi @skybluecat, thanks for the tip, haven't really delved into WebGL2 since THREE don't officially support it yet.
Just making sure we're on the same page, you're talking about this right:

https://github.com/RonenNess/partykals/blob/master/partykals/material/shaders/fragment.js#L25

Or something else I should notice?
Thanks!

**Comment by skybluecat** [comment]
Yes, and also `vec4 texture` on line 44.
